# $schema=https://www.schemastore.org/github-workflow.json
on:
  release:
    types:
      - created
  push:
    tags:
      - "v*.*.*"

name: release

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Build package distributions
        run: uv build

      - name: Publish to PyPI
        run: uv publish
